spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newspaper?allowPublicKeyRetrieval=true&useSSL=false
    username: develop
    password: develop
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  address: localhost
  port: 8080

management:
  server:
    port: 8081 # Actuator работает на отдельном порту
  security:
    enabled: false  # Если нужно отключить безопасность для актюаторов
  endpoints:
    web:
      exposure:
        include: "*"  # Разрешить доступ ко всем эндпоинтам
  endpoint:
    mappings:
      enabled: true  # Включить эндпоинт mappings, который показывает все доступные маршруты
