spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newspaper?allowPublicKeyRetrieval=true&useSSL=false
    username: dev
    password: development
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
